# Numpy Tutorial

The tutorial on NumPy is heavily borrowed from the NumPy website; [https://numpy.org/devdocs/user/quickstart.html](https://numpy.org/devdocs/user/quickstart.html)

NumPy (num-pie) or "Numerical Python" is a Python library that undergirds almost all of Python's advanced mathematical and statistical functions. You might not use it too much directly but you'll be interacting with it constantly through other libraries. 

The core of NumPy are the NumPy arrays which are kind of like very advanced Python Lists.

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In the code block above, a is a 1-dimensional array. 

In [4]:
c = np.array([2, 3, 4, 5, 6, 2]).reshape(2, 3)
c

array([[2, 3, 4],
       [5, 6, 2]])

In the code block above, c is a 2-dimensional array, basically a table. 

In [6]:
d = np.array([2, 3, 4, 5, 6, 2, 3, 5]).reshape(2, 2, 2)
d

array([[[2, 3],
        [4, 5]],

       [[6, 2],
        [3, 5]]])

In the code block above d is a 3-dimensional array

## NumPy Calculations

In [7]:
e = np.array([1, 2, 3, 4, 5, 6])
print(e.sum()) # Sum the array
print(e.min()) # Find the minimum value in an array
print(e.max()) # Find the maximum value in an array
print(e.mean()) # Find the arithmetic mean of an array


21
1
6
3.5


## Special NumPy Arrays

These are some useful arrays that you can quickly create in NumPy. Don't worry too much about learning them now but it'll be useful to have a cheatsheet of them nearby. 

In [14]:
np.zeros(5) # Creates an array of zeros with 5 elements


array([0., 0., 0., 0., 0.])

In [15]:
np.linspace(0, 6, 10) # Creates an array of values from 0 through 6 in 10 even spaces


array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [16]:
np.random.rand(3) # Three random values between 0 and 1


array([0.29184781, 0.02903337, 0.3392823 ])

In [12]:
np.random.randint(1, 1000) # A random integer between 1 and 1000


127

In [13]:
np.arange(25) # Like the "Range" function we learned earlier, this is gives you a range of integers between 1 - 25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])